export default {
    SET_TOP_ANIMES: "SET_TOP_ANIMES",
    SET_TOP_MANGAS: "SET_TOP_MANGAS",
    SET_ANIME_DESCRIPTION: "SET_ANIME_DESCRIPTION",
    SET_MANGA_DESCRIPTION: "SET_MANGA_DESCRIPTION"
}
  